### ISSUE TITLE
Thold fails after php upgrade

### ISSUE THREAD

**Issue by rtripon** [Cacti/plugin_thold#456]
Hello,
I had to upgrade to php 7.4 and now it seems that thold is failing, got some errors :

2020/11/03 11:15:19 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler())
2020/11/03 11:15:19 - ERROR PHP ERROR: Uncaught TypeError: Argument 9 passed to mailer() must be of the type array, string given, called in /var/www/html/cacti/plugins/thold/thold_functions.php on line 5449 and defined in /var/www/html/cacti/lib/functions.php:3447 Stack trace: #0 /var/www/html/cacti/plugins/thold/thold_functions.php(5449): mailer() #1 /var/www/html/cacti/plugins/thold/includes/polling.php(739): thold_mail() #2 /var/www/html/cacti/plugins/thold/includes/polling.php(46): thold_update_host_status() #3 /var/www/html/cacti/lib/plugins.php(181): thold_poller_bottom() #4 /var/www/html/cacti/lib/plugins.php(75): api_plugin_run_plugin_hook() #5 /var/www/html/cacti/poller.php(826): api_plugin_hook() #6 {main} thrown in file: /var/www/html/cacti/lib/functions.php on line: 3447 

2020/11/03 11:10:26 - CMDPHP SQL Backtrace: (/poller.php[681]:process_poller_output(), /lib/poller.php[544]:api_plugin_hook_function(), /lib/plugins.php[117]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[225]:thold_poller_output(), /plugins/thold/includes/polling.php[375]:db_fetch_assoc(), /lib/database.php[476]:db_fetch_assoc_prepared(), /lib/database.php[490]:db_execute_prepared())
2020/11/03 11:10:26 - CMDPHP ERROR: A DB Row Failed!, Error: Unknown column 'td.upper_ds' in 'field list'
2020/11/03 11:10:25 - CMDPHP SQL Backtrace: (/poller.php[697]:process_poller_output(), /lib/poller.php[544]:api_plugin_hook_function(), /lib/plugins.php[117]:api_plugin_run_plugin_hook_function(), /lib/plugins.php[225]:thold_poller_output(), /plugins/thold/includes/polling.php[375]:db_fetch_assoc(), /lib/database.php[476]:db_fetch_assoc_prepared(), /lib/database.php[490]:db_execute_prepared()) 

Cacti version is 1.3.0 devel on Centos 7 with php 7.4, and I upgraded thold also with a git pull.

**Comment by TheWitness** [comment]
Yea, I would avoid the 'develop' branch for a while.  @netniV made a change that fundamentally is going to break things everywhere, and we are all busy right now on other things.

**Comment by TheWitness** [comment]
Here is the creation logic for thold_data.  You will have to make the changes by hand, but it would be good to know from what version you upgraded from:

```sql
SHOW CREATE TABLE thold_data;

CREATE TABLE `thold_data` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `name` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `name_cache` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `local_data_id` int(11) NOT NULL DEFAULT 0,
  `data_template_rrd_id` int(11) NOT NULL DEFAULT 0,
  `local_graph_id` int(11) NOT NULL DEFAULT 0,
  `graph_template_id` int(11) NOT NULL DEFAULT 0,
  `data_template_id` int(11) NOT NULL DEFAULT 0,
  `data_template_hash` varchar(32) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `data_source_name` varchar(100) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `thold_hi` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `thold_low` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `thold_fail_trigger` int(10) unsigned DEFAULT NULL,
  `thold_fail_count` int(11) NOT NULL DEFAULT 0,
  `time_hi` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `time_low` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `time_fail_trigger` int(12) NOT NULL DEFAULT 1,
  `time_fail_length` int(12) NOT NULL DEFAULT 1,
  `thold_warning_hi` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `thold_warning_low` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `thold_warning_fail_trigger` int(10) unsigned DEFAULT NULL,
  `thold_warning_fail_count` int(11) NOT NULL DEFAULT 0,
  `time_warning_hi` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `time_warning_low` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `time_warning_fail_trigger` int(12) NOT NULL DEFAULT 1,
  `time_warning_fail_length` int(12) NOT NULL DEFAULT 1,
  `thold_alert` int(1) NOT NULL DEFAULT 0,
  `prev_thold_alert` int(1) NOT NULL DEFAULT 0,
  `thold_enabled` enum('on','off') COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT 'on',
  `thold_type` int(3) NOT NULL DEFAULT 0,
  `bl_ref_time_range` int(10) unsigned DEFAULT NULL,
  `bl_pct_down` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bl_pct_up` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `bl_fail_trigger` int(10) unsigned DEFAULT NULL,
  `bl_fail_count` int(11) unsigned DEFAULT NULL,
  `bl_alert` int(2) NOT NULL DEFAULT 0,
  `bl_thold_valid` int(10) unsigned NOT NULL DEFAULT 0,
  `lastread` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `lasttime` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `lastchanged` timestamp NOT NULL DEFAULT '0000-00-00 00:00:00',
  `oldvalue` varchar(100) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `repeat_alert` int(10) unsigned DEFAULT NULL,
  `notify_extra` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `notify_warning_extra` varchar(512) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `notify_warning` int(10) unsigned DEFAULT NULL,
  `notify_alert` int(10) unsigned DEFAULT NULL,
  `snmp_event_category` varchar(255) COLLATE utf8mb4_unicode_ci DEFAULT NULL,
  `snmp_event_severity` tinyint(1) NOT NULL DEFAULT 3,
  `snmp_event_warning_severity` tinyint(1) NOT NULL DEFAULT 2,
  `thold_daemon_pid` varchar(25) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `host_id` int(10) DEFAULT NULL,
  `syslog_priority` int(2) NOT NULL DEFAULT 3,
  `syslog_facility` int(2) DEFAULT NULL,
  `syslog_enabled` char(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `data_type` int(12) NOT NULL DEFAULT 0,
  `show_units` char(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `cdef` int(11) NOT NULL DEFAULT 0,
  `percent_ds` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `expression` varchar(512) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `upper_ds` varchar(64) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `thold_template_id` int(11) NOT NULL DEFAULT 0,
  `template_enabled` char(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `tcheck` int(1) NOT NULL DEFAULT 0,
  `exempt` char(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `acknowledgment` char(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `thold_hrule_alert` int(11) unsigned DEFAULT NULL,
  `thold_hrule_warning` int(11) unsigned DEFAULT NULL,
  `restored_alert` char(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `reset_ack` char(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `persist_ack` char(3) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `email_body` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `email_body_warn` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `email_body_restoral` varchar(1024) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `trigger_cmd_high` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `trigger_cmd_low` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `trigger_cmd_norm` varchar(255) COLLATE utf8mb4_unicode_ci NOT NULL DEFAULT '',
  `notes` varchar(1024) COLLATE utf8mb4_unicode_ci DEFAULT '',
  PRIMARY KEY (`id`),
  KEY `host_id` (`host_id`),
  KEY `local_data_id` (`local_data_id`),
  KEY `data_template_rrd_id` (`data_template_rrd_id`),
  KEY `local_graph_id` (`local_graph_id`),
  KEY `thold_template_id` (`thold_template_id`),
  KEY `thold_enabled` (`thold_enabled`),
  KEY `template_enabled` (`template_enabled`),
  KEY `tcheck` (`tcheck`),
  KEY `thold_daemon_pid` (`thold_daemon_pid`)
) ENGINE=InnoDB AUTO_INCREMENT=260 DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci ROW_FORMAT=DYNAMIC COMMENT='Threshold data'
```

**Comment by TheWitness** [comment]
This will be your solution for now.
