### ISSUE TITLE
Critical ERROR. Mistake on file thold_functions.php

### ISSUE THREAD

**Issue by pautiina** [Cacti/plugin_thold#47]
```
2017-02-14 14:04:16 - ERROR PHP ERROR in  Plugin 'thold': Uncaught Error: [] operator not supported for strings in /var/www/cacti/plugins/thold/thold_functions.php:1621
Stack trace:
#0 /var/www/cacti/plugins/thold/includes/polling.php(229): thold_check_threshold(Array)
#1 /var/www/cacti/plugins/thold/includes/polling.php(35): thold_check_all_thresholds()
#2 /var/www/cacti/lib/plugins.php(161): thold_poller_bottom(Array)
#3 /var/www/cacti/lib/plugins.php(68): api_plugin_run_plugin_hook('poller_bottom', 'thold', 'thold_poller_bo...', Array)
#4 /var/www/cacti/poller.php(717): api_plugin_hook('poller_bottom')
#5 {main}
  thrown in file: /var/www/cacti/plugins/thold/thold_functions.php on line: 1621
```
The line 1621 must be:
`			$file_array = array(`
After this change and chnge on Issue  #46  all works.

**Comment by cigamit** [comment]
Resolved, thanks for testing!
