### ISSUE TITLE
Thold plugin issue

### ISSUE THREAD

**Issue by mmehsan1** [Cacti/plugin_thold#572]
New to to cacti and thold plugin.
installed this plugin to get some notifications. getting the following error.
anyone can help

Thold version   1.6 
Cacti version  1.2.19

2023-01-23 10:29:18 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'thold'
--
2023-01-23 10:29:18 - ERROR PHP ERROR in  Plugin 'thold': Uncaught  Error: Call to undefined function get_policies() in  /opt/cacti-1.2.19/plugins/thold/thold_functions.php:1200 Stack trace: #0  /opt/cacti-1.2.19/plugins/thold/thold_graph.php(436):  get_allowed_thresholds() #1  /opt/cacti-1.2.19/plugins/thold/thold_graph.php(56): tholds() #2 {main}  thrown in file: /opt/cacti-1.2.19/plugins/thold/thold_functions.php on  line: 1200
2023-01-23 09:55:53 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'thold'
2023-01-23 09:55:53 - ERROR PHP ERROR in  Plugin 'thold': Uncaught  Error: Call to undefined function get_policies() in  /opt/cacti-1.2.19/plugins/thold/thold_functions.php:1200 Stack trace: #0  /opt/cacti-1.2.19/plugins/thold/thold_graph.php(436):  get_allowed_thresholds() #1  /opt/cacti-1.2.19/plugins/thold/thold_graph.php(56): tholds() #2 {main}  thrown in file: /opt/cacti-1.2.19/plugins/thold/thold_functions.php on  line: 1200

**Comment by TheWitness** [comment]
Upgrade Cacti to 1.2.23.
