### ISSUE TITLE
Call to undefined function thold_check_upgrade()

### ISSUE THREAD

**Issue by dsclassen** [Cacti/plugin_thold#71]
fresh git pull into latest cacti. Receive this error when trying to enable thold plugin:

```
2017-04-11 13:48:14 - ERROR PHP ERROR in  Plugin 'thold': Uncaught Error: Call to undefined function thold_check_upgrade() in /cacti/plugins/thold/includes/arrays.php:306
Stack trace:
#0 /cacti/plugins/thold/includes/polling.php(231): include()
#1 /cacti/plugins/thold/includes/polling.php(35): thold_check_all_thresholds()
#2 /cacti/lib/plugins.php(161): thold_poller_bottom(Array)
#3 /cacti/lib/plugins.php(68): api_plugin_run_plugin_hook('poller_bottom', 'thold', 'thold_poller_bo...', Array)
#4 /cacti/poller.php(717): api_plugin_hook('poller_bottom')
#5 {main}
  thrown in file: /cacti/plugins/thold/includes/arrays.php on line: 306
2017-04-11 13:48:14 - CMDPHP PHP ERROR Backtrace: (CactiShutdownHandler)(/lib/functions.php: 4300 cacti_debug_backtrace)
2017-04-11 13:48:14 - CMDPHP ERRORS DETECTED - DISABLING PLUGIN 'thold'

```

**Comment by cigamit** [comment]
This is resolve now.  Sorry about that.
